### ISSUE TITLE
Existence of devDependencies causes .less modules not to load in CanJS project

### ISSUE THREAD

**Issue by akagomez** [stealjs/system-npm#74] opened 2015-08-16 22:29 UTC
My project (https://github.com/akagomez/akagomez.com) reports an error when `devDependencies` is defined in my `package.json`: 

```
Uncaught Error: Unable to load dependency less@2.4.0#index. steal.js:3508getModule steal.js:3508
Potentially unhandled rejection [5] Error loading "src/component/layout/layout.less!$less" at <unknown>
Error loading "src/component/layout/layout.less!$less" from "src/component/layout/layout" at http://localhost/~akagomez/akagomez/akagomez.com/src/component/layout/layout.js
Error loading "$less" at http://localhost/~akagomez/akagomez/akagomez.com/node_modules/steal/ext/less.js
Error evaluating http://localhost/~akagomez/akagomez/akagomez.com/node_modules/steal/ext/less.js
Uncaught Error: Unable to load dependency less@2.4.0#index. (WARNING: non-Error used) 
```

Working `package.json`:

```
{
  "name": "akagomez.com",
  "version": "0.0.0",
  "description": "The personal website of Chris Gomez (akagomez@gmail.com)",
  "main": "index.js",
  "scripts": {
    "test": "grunt test"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/akagomez/akagomez.git"
  },
  "author": "Chris Gomez",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/akagomez/akagomez/issues"
  },
  "homepage": "https://github.com/akagomez/akagomez",
  "dependencies": {
    "bootstrap": "^3.3.5",
    "bootswatch": "^3.3.5",
    "can": "^2.3.0-pre.4",
    "jquery": "^2.1.4",
    "marked": "^0.3.5",
    "steal": "^0.11.0-pre.1"
  }
}
```

Broken `package.json`:

```
{
  "name": "akagomez.com",
  "version": "0.0.0",
  "description": "The personal website of Chris Gomez (akagomez@gmail.com)",
  "main": "index.js",
  "scripts": {
    "test": "grunt test"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/akagomez/akagomez.git"
  },
  "author": "Chris Gomez",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/akagomez/akagomez/issues"
  },
  "homepage": "https://github.com/akagomez/akagomez",
  "dependencies": {
    "bootstrap": "^3.3.5",
    "bootswatch": "^3.3.5",
    "can": "^2.3.0-pre.4",
    "jquery": "^2.1.4",
    "marked": "^0.3.5",
    "steal": "^0.11.0-pre.1"
  },
  "devDependencies": {
    "serve": "^1.4.0"
  }
}
```

**Comment by matthewp** [comment] 2015-08-16 22:48
It's not the existence of devDevdependencies, it's the one that you have. You can ignore it with `"system": { "npmIgnore": [ "serve" ] }` or `"system": { "npmIgnore": [ "devDependencies" ] }` to ignore all devDependencies.  #41 covers the root problem here.

**Comment by akagomez** [comment] 2015-08-16 22:50
I see. Thanks for the clarification.

**Comment by BigAB** [comment] 2015-11-12 02:43
So... close then?

**Comment by matthewp** [comment] 2015-11-12 04:13
Yes, we can call this a duplicate of 41.

**Closed by matthewp** 2015-11-12 04:13 UTC
